// Retos por nivel. Se muestran cuando un jugador acumula 3 fallos seguidos.
// Nivel 1: Retos sociales y divertidos.
// Nivel 2: Retos atrevidos / de pareja / coqueteos.
// Nivel 3: Retos picantes / incomodos / comprometedores.

export const CHALLENGES: Record<1 | 2 | 3 | 4, string[]> = {
  1: [
    'Imita a alguien de este grupo durante 30 segundos hasta que adivinen quien es.',
    'Deja que el grupo te inspeccione los mensajes recientes de WhatsApp durante 10 segundos.',
    'Llama a alguien de tus contactos y dile que te sientes muy orgulloso/a de el/ella.',
    'Haz tu mejor baile sin musica durante 20 segundos.',
    'Confiesa cual de los presentes te cae peor y por que.',
    'Deja que el grupo elija un estado de WhatsApp y te lo ponga durante 1 hora.',
    'Habla con acento extranjero durante las proximas 2 rondas.',
    'Deja que alguien del grupo lea en voz alta la ultima busqueda en tu Google.',
    'Imita a tu papa o mama regañandote. El grupo vota si es creible.',
    'Cuenta el chisme mas reciente que sabes sin decir nombres.',
    'Escribe un elogio sincero sobre la persona a tu izquierda y leelo en voz alta.',
    'Haz 10 sentadillas mientras cantas el coro de una cancion que elija el grupo.',
    'Muestrale al grupo la foto mas rara o vergonzosa que tengas guardada en tu celular.',
    'Actua como si fueras el presentador de un noticiero y da las ultimas noticias de este grupo.',
    'Confiesa cual de los presentes te parece el mas chismoso y da tus razones.',
    'Manda un mensaje al chat familiar diciendo alguien mas tiene hambre, luego muestralo.',
    'Deja que el grupo revise tu lista de reproduccion y critiquen tu gusto musical.',
    'Haz tu mejor chiste. El grupo vota si se rien o no.',
    'Cuenta un secreto tuyo que ninguno de los presentes sepa.',
    'Haz una pose de modelo durante 30 segundos sin reirte.',
  ],
  2: [
    'Susurra algo seductor al oido de la persona que elija el grupo.',
    'Escribe un mensaje coqueto y enviaselo a la persona que el grupo elija de tus contactos.',
    'Deja que alguien del grupo te ponga un apodo intimo y te llamen asi el resto de la noche.',
    'Muestrale al grupo los ultimos emojis que usaste con tu ex o tu pareja.',
    'Sientate en el regazo de la persona que el grupo elija durante la proxima ronda.',
    'Deja que el grupo le escriba un mensaje comprometedor a quien quieran desde tu celular.',
    'Confiesa quien de los presentes te parece mas atractivo/a fisicamente.',
    'Haz contacto visual profundo con la persona que el grupo elija durante 30 segundos sin hablar.',
    'Describe tu ex mas apasionado/a sin decir nombres pero con suficiente detalle para que adivinen.',
    'Da un masaje de hombros de 30 segundos a quien el grupo decida.',
    'Toma la mano de la persona a tu derecha y no la sueltes hasta la proxima pregunta.',
    'Confiesa la mentira mas grande que le has dicho a una pareja.',
    'El grupo elige a alguien: debes decirle 3 cosas que te atraen de esa persona.',
    'Revela el nombre del contacto mas inapropiado que tienes guardado en tu celular.',
    'Escenifica como fue tu primera cita con tu primer amor real (actuacion de 1 min).',
    'Deja que el grupo elija un estado de historia para Instagram y lo publiques ahora.',
    'Describe sin decir el nombre a la persona con quien tuviste el beso mas memorable.',
    'Haz lo que la persona a tu izquierda te ordene... siempre que no cruce la linea.',
    'Confiesa cual es tu senal de que alguien te gusta y cuando fue la ultima vez que la activaste.',
    'El grupo elige: dale like a una foto vieja (min. 2 anos) del ex de alguien presente.',
  ],
  3: [
    'Muestrale al grupo el mensaje mas subido de tono que tengas enviado o recibido.',
    'Besa la mejilla de la persona que el grupo elija, y ellos deciden cuanto tiempo.',
    'Lee en voz alta y sin editar la ultima conversacion intima que tengas guardada.',
    'El grupo elige a quien: debes sentarte encima de esa persona durante la proxima ronda.',
    'Confiesa en detalle el encuentro mas atrevido o loco que hayas tenido.',
    'Deja que el grupo huela tu celular desbloqueado y busque lo que quiera en tu galeria durante 15 segundos.',
    'Describe sin censura que harias si estuvieras a solas con la persona que el grupo elija.',
    'El grupo te dicta un mensaje y debes enviarselo al contacto que ellos elijan.',
    'Confiesa el lugar mas raro o inapropiado donde hayas tenido un encuentro intimo.',
    'Actua durante 30 segundos como eres en la intimidad. Sin palabras, solo gestos.',
    'El grupo te hace una pregunta nivel 3 adicional y no puedes negarte a responder.',
    'Llama a la persona con la que saliste hace mas tiempo y di: te pienso a veces.',
    'Muestrale al grupo tu historial de busqueda durante los ultimos 3 dias.',
    'Confiesa cuantas personas de este grupo han sido protagonistas de uno de tus pensamientos.',
    'Haz tu imitacion mas atrevida de alguien que todos en el grupo conozcan.',
    'Deja que el grupo elija una foto tuya y la publiquen en tu historia de Instagram ahora mismo.',
    'El grupo vota: debes enviarle un audio de voz comprometedor a quien ellos decidan.',
    'Revela el secreto mas oscuro que guardas de alguien presente en esta sala.',
    'Describe tu tipo ideal en la cama con detalle. El grupo adivina a quien de los presentes se parece.',
    'El grupo decide: beberas lo que elijan, haras lo que elijan, o confiesas lo que elijan. Elige una.',
  ],
  4: [
    'El grupo inventa un castigo exclusivo y personalizado para ti ahora mismo.',
    'Confiesa la verdad sobre la persona que escribió la última pregunta.',
    'Deja que el grupo elija a quién de los presentes debes darle un abrazo de 20 segundos.',
    'Imita la risa o la pose típica de quien esté a tu derecha.',
    'El grupo decide un trago o penitencia personalizada para ti.',
    'Confiesa cuál pregunta de este pack personalizado te dio más miedo que te tocara.',
    'Muestra la última foto que tomaste con alguien de este grupo.',
    'Deja que el jugador con más puntos elija tu castigo.',
    'Haz un brindis con dedicatoria vergonzosa para el grupo.',
    'Cuenta la historia real detrás de una de las preguntas personalizadas del grupo.',
    'Deja que el grupo te cambie el nombre en el juego por el apodo más ridículo.',
    'El grupo elige: responder la siguiente pregunta o cumplir 2 retos seguidos.',
    'Describe el peor defecto y la mejor cualidad de la persona a tu izquierda.',
    'Pasa tu teléfono desbloqueado a la persona de enfrente por 10 segundos.',
    'Haz una videollamada a quien el grupo elija y cuelga en 3 segundos.',
    'Confiesa un chisme que juraste no contar sobre alguien del grupo.',
    'El grupo vota: debes confesar tu mayor secreto o invitar la próxima ronda.',
    'Haz una declaración de amor exagerada y dramática a quien el grupo elija.',
    'Muestra tu última nota guardada o recordatorio en el celular.',
    'Cumple una orden directa que el grupo vote por mayoría.',
  ],
};
