import type { Question } from '../types/game';

export const QUESTIONS: Question[] = [
  // ——— Nivel 1: Conociéndonos ———
  { id: 'q-l1-01', text: '¿Quién del grupo sería capaz de fingir que le encanta un regalo horrible solo para no herir sentimientos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-02', text: '¿Cuál fue la peor cita o salida que has tenido y qué hiciste para escapar con dignidad?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-03', text: '¿Qué canción pondrías como soundtrack de tu peor decisión del último año?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-04', text: '¿Cuál es la cosa más rara que has comido y no te arrepientes?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-05', text: 'Si tuvieras que describir tu vida amorosa como una película, ¿qué género sería y por qué?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-06', text: '¿Cuál es tu mayor miedo irracional que te da pena admitir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-07', text: '¿Has olido tu ropa interior usada antes de decidir si te la pones de nuevo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-08', text: '¿Qué es lo más asqueroso o antihigiénico que has hecho cuando estabas completamente solo/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-09', text: '¿Te has hurgado la nariz y te has comido un moco siendo ya mayor de edad?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-10', text: '¿Has tenido un accidente estomacal (hacerte encima) siendo ya un adulto?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-11', text: '¿Has olido deliberadamente tus axilas o alguna parte de tu cuerpo para comprobar si olías mal?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-12', text: '¿Qué es lo más juzgable que has buscado en el historial de tu navegador en modo incógnito?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-13', text: '¿Has revisado la basura, cajones o pertenencias privadas de alguien por pura chismosería?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-14', text: '¿Alguna vez te has atribuido el mérito o trabajo de otra persona para quedar bien ante un jefe o profesor?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-15', text: '¿Has hablado mal de tu mejor amigo o amiga a sus espaldas para quedar bien con otras personas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-16', text: '¿Has robado dinero u objetos a un familiar o amigo cercano, aunque fuera algo de poco valor?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-17', text: '¿Alguna vez has deseado en secreto que a alguien de tu entorno le fuera mal en la vida?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-18', text: '¿Cuál es el secreto más oscuro que mantienes oculto de tus padres?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-19', text: '¿Has fingido una enfermedad o emergencia grave solo para evitar una responsabilidad o llamar la atención?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-20', text: '¿Alguna vez te has quedado con dinero encontrado o ajeno sabiendo exactamente a quién le pertenecía?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-21', text: '¿Has sentido placer o alivio cuando le ocurrió una desgracia a alguien que te caía muy mal?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-22', text: '¿Cuál es la mentira más grande que le has sostenido a tu familia durante años y que aún no descubren?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-23', text: '¿Qué es lo más bajo o humillante que has hecho por conseguir dinero rápido?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-24', text: '¿Has fingido que te caía bien alguien únicamente para sacarle un beneficio personal o económico?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-25', text: '¿Has sentido que tus amigos solo te toleran y que en realidad no le importas a nadie del grupo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-26', text: 'Si estuvieras obligado a elegir entre salvar la vida de tu mascota o la de un desconocido, ¿a quién salvarías?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-27', text: '¿Alguna vez has sentido envidia profunda hacia el éxito o la apariencia de un familiar cercano?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-28', text: '¿Qué es lo más feo o mezquino que has pensado sobre el aspecto físico de tu mejor amigo/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-29', text: '¿Por qué tomas alcohol realmente? ¿Para divertirte, por presión o para encajar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-30', text: 'Sinceramente, ¿crees que estás preparado/a para tener hijos en el futuro o sientes que serías un desastre?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-31', text: '¿Cuál es la mentira piadosa que más veces has repetido este año?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-32', text: '¿Qué comida defiendes a muerte aunque todo el mundo a tu alrededor la odie?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-33', text: '¿Cuál ha sido tu peor corte de pelo o cambio de look y cuánto tardaste en superarlo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-34', text: '¿Qué aplicación de tu celular borrarías de inmediato si supieras que alguien va a revisártelo ahora mismo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-35', text: '¿Cuál es el chisme más pesado que sabes de alguien de tu trabajo o lugar de estudio?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-36', text: '¿Qué serie, película o novela ves a escondidas porque te da pena admitir que te gusta?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-37', text: '¿Cuál ha sido tu excusa más absurda para llegar tarde a un compromiso importante?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-38', text: '¿A quién de tus amigos imitarías si tuvieras que hacer un show de comedia sobre ellos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-39', text: '¿Cuál fue la peor decisión de moda o ropa que tomaste durante tu adolescencia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-40', text: '¿Qué canción te sabes de memoria de principio a fin pero jamás la cantarías en público?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-41', text: '¿Cuál ha sido el peor regalo que has dado o recibido en un intercambio?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-42', text: '¿Qué cosa rara haces cuando estás completamente solo/a en tu cuarto que jamás harías con testigos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-43', text: '¿Cuál es tu mayor manía o costumbre extraña antes o después de dormir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-44', text: '¿A qué famoso o creador de contenido sigues fielmente aunque sabes que su contenido es pésimo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-45', text: '¿Cuál fue la exposición o examen en el que hiciste el peor papel de tu vida y cómo sobreviviste?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-46', text: '¿Qué es lo más innecesario que has comprado por impulso y que terminó agarrando polvo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-47', text: '¿Cuál es tu teoría de conspiración favorita que defiendes aunque no tenga sentido?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-48', text: '¿Qué muletilla o frase usas tanto que la gente ya te la señala con molestia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-49', text: '¿Cuál fue la mentira más elaborada que inventaste para faltar al colegio, universidad o trabajo?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-50', text: '¿Qué es lo más vergonzoso que se te ha caído, manchado o roto en una reunión pública?', level: 1, genderTarget: 'M' },
  { id: 'q-l1-51', text: '¿Cuál es el hábito de convivencia que más te desespera de otras personas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-52', text: '¿Qué red social o perfil revisas compulsivamente sin darte cuenta varias veces al día?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-53', text: '¿Cuál fue tu obsesión o fanatismo más intenso y ridículo durante la infancia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-54', text: '¿Qué mentira piadosa te dijeron tus padres de niño y que creíste hasta que fuiste bastante grande?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-55', text: '¿Cuál es tu peor costumbre o mala educación al momento de comer?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-56', text: '¿A qué personaje o famoso dicen que te pareces y odias profundamente que te lo recuerden?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-57', text: '¿Cuál fue el peor consejo de vida o estudio que seguiste al pie de la letra y salió mal?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-58', text: '¿Cuál ha sido tu peor experiencia en una entrevista laboral o entrega de proyecto?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-59', text: '¿Qué cosa o actividad finges que te encanta solo para no desencajar en tu grupo de amigos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-60', text: '¿Cuál es tu mayor superstición absurda a la que le tienes miedo sincero?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-61', text: '¿Qué objeto o juguete de tu infancia todavía conservas guardado en secreto?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-62', text: '¿Cuál fue el peor consejo amoroso que le diste a un amigo/a y que arruinó las cosas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-63', text: '¿Qué influencer o figura pública te cae insoportablemente mal sin una razón lógica?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-64', text: '¿Cuál fue tu peor pasado de copas o bochorno en una reunión familiar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-65', text: '¿Qué costumbre extraña o manía tiene tu familia que a ti te parece normal pero a los demás no?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-66', text: '¿Qué error absurdo cometiste cuando estabas aprendiendo a manejar o andar en bicicleta?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-67', text: '¿Cuál fue el apodo más feo o vergonzoso que te pusieron en la escuela?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-68', text: '¿Qué es lo más ridículo o exagerado por lo que has llorado en el último año?', level: 1, genderTarget: 'M' },
  { id: 'q-l1-69', text: '¿Cuál fue tu peor recuerdo de una excursión, paseo o viaje escolar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-70', text: '¿Qué combinación rara de comida haces que a los demás les da asco pero a ti te fascina?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-71', text: '¿Cuál fue el mensaje de texto comprometedor que enviaste al chat equivocado y quisiste desaparecer?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-72', text: '¿Cuál ha sido tu peor desastre intentando cocinar un platillo elaborado?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-73', text: '¿Cuál fue la broma más pesada que le hiciste a alguien o que te hicieron a ti?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-74', text: '¿Qué cosa valiosa perdiste por descuido y inventaste una historia falsa para no aceptar la culpa?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-75', text: '¿Cuál fue tu peor actuación fingiendo estar enfermo para librarte de un compromiso?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-76', text: '¿Qué es lo más absurdo o bizarro que has soñado y que recuerdas con total claridad?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-77', text: '¿Cuál fue la pelea más tonta e insignificante que tuviste con tu mejor amigo/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-78', text: '¿Qué es lo más desordenado o sucio de tu cuarto que te daría pena que otros vieran?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-79', text: '¿Cuál fue el peor oso o ridículo que hiciste en un karaoke o pista de baile?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-80', text: '¿Qué hábito tuyo te hace sentir que estás envejeciendo antes de tiempo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-81', text: '¿Cuál es la mentira más tonta que dijiste de niño y que sigues sosteniendo por diversión?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-82', text: '¿Qué logro insignificante te da muchísimo orgullo pero te da pena presumirlo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-83', text: '¿Cuál fue tu peor experiencia probándote ropa en una tienda o centro comercial?', level: 1, genderTarget: 'M' },
  { id: 'q-l1-84', text: '¿Cuál fue la foto de perfil más fea o cringe que llegaste a tener en tus redes sociales?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-85', text: '¿Qué es lo más vergonzoso que te ha pasado en el transporte público o un taxi?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-86', text: '¿Qué cosa pides o haces en un restaurante que a tus acompañantes les da vergüenza ajena?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-87', text: '¿Cuál fue el peor apodo secreto que le pusiste a un profesor, jefe o conocido?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-88', text: '¿Qué es lo más raro o tonto que has hecho mientras esperabas solo/a en un lugar público?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-89', text: '¿Cuál ha sido la peor excusa que has puesto para dejar en "visto" a alguien por días?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-90', text: '¿Qué cara o gesto haces cuando tienes que disimular que alguien que no te agrada te está hablando?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-91', text: '¿Cuál fue la peor decisión que tomaste simplemente por seguirle el juego a tus amigos?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-92', text: '¿Qué es lo que más te avergüenza de tu historial de reproducciones de música o videos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-93', text: '¿Qué es lo más tonto por lo que te has sentido juzgado físicamente por desconocidos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-94', text: '¿Qué reacción ridícula tienes cuando te asustas de verdad en público?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-95', text: '¿Qué es lo peor que hiciste para ganar una apuesta tonta entre amigos?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-96', text: '¿Qué haces cuando ves a alguien conocido en la calle y quieres evitar saludarlo a toda costa?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-97', text: '¿Cuál fue el momento más incómodo que viviste en una consulta médica o dental?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-98', text: '¿Qué haces cuando se te olvida por completo el nombre de alguien que te acaba de saludar con cariño?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-99', text: '¿Cuál fue la compra más absurda o inservible que hiciste solo porque estaba en oferta?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-100', text: '¿Qué es lo primero que harías si te dieran acceso al celular de cualquier persona de este grupo durante 5 minutos?', level: 1, genderTarget: 'all' },

  // ——— Nivel 2: Juego previo ———
  { id: 'q-l2-01', text: '¿Quién la tiene más grande, tu ex o tu novio actual (o tu penúltimo ex)?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-02', text: '¿Quién tiene la vagina más apretada, tu ex o tu actual novia (o tu penúltima ex)?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-03', text: '¿Has revisado el celular, mensajes o historial de tu pareja a sus espaldas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-04', text: '¿Has fingido un orgasmo con tu pareja actual o última para que la relación terminara rápido?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-05', text: '¿Has estado con una chica a la que le olía mal su zona íntima? ¿Cómo reaccionaste?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-06', text: '¿Alguna vez te ha gustado o has intentado coquetear con la pareja de un amigo o amiga?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-07', text: '¿Has mentido sobre tu experiencia o desempeño en la cama para parecer más experimentado/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-08', text: '¿Has rechazado o sentido vergüenza de salir con alguien únicamente por su aspecto físico?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-09', text: '¿Has mirado las redes sociales de tu ex de forma obsesiva estando ya en una nueva relación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-10', text: '¿Has comparado el desempeño íntimo de tu pareja actual con el de tu ex y tu pareja actual perdió?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-11', text: '¿Alguna vez te dio vergüenza que te vieran en público con tu pareja por cómo iba vestida o actuaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-12', text: '¿Has estado con alguien solo por interés económico, estatus o para no sentirte solo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-13', text: '¿Se te ha escapado un pedo o mal olor corporal durante un acto íntimo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-14', text: 'Si tu pareja subiera drásticamente de peso o cambiara físicamente de forma negativa, ¿la dejarías?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-15', text: '¿Has manipulado emocionalmente a alguien amenazando con hacerte daño para que no te dejara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-16', text: '¿Qué es lo peor que has dicho sobre la familia de tu pareja a sus espaldas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-17', text: '¿Has dejado a alguien por mensaje o haciendo ghosting porque te dio pereza afrontar la conversación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-18', text: '¿Alguna vez has continuado una relación íntima con alguien solo porque no sabías cómo terminarle?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-19', text: '¿Cuál es la peor mentira que le has dicho a una cita para llevártela a la cama?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-20', text: '¿Qué mensaje de texto picante has reescrito mil veces y nunca te atreviste a enviar?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-21', text: '¿Alguna vez has fingido interés en un tema aburrido solo para lograr besar a alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-22', text: '¿Cuál es la zona de tu cuerpo que más te da inseguridad cuando te desnudas ante alguien nuevo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-23', text: '¿Alguna vez has borrado un chat entero por miedo a que tu pareja o ligue lo descubriera?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-24', text: '¿Qué es lo más ridículo que has hecho para llamar la atención de la persona que te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-25', text: '¿Te has sentido atraído/a por algún profesor, jefe o figura de autoridad mientras estabas en una relación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-26', text: '¿Alguna vez has dudado seriamente de tu orientación sexual debido a un pensamiento o sueño específico?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-27', text: '¿Qué es lo más bajo que has hecho por venganza amorosa hacia una expareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-28', text: '¿Has estado a punto de serle infiel a tu pareja y te echaste para atrás a último segundo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-29', text: '¿Alguna vez le dijiste "te amo" a alguien sin sentirlo, solo para no arruinar el momento?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-30', text: '¿Qué es lo más tóxico que has hecho por celos compulsivos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-31', text: '¿Cuál ha sido tu beso más desagradable o peor ejecutado y por qué?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-32', text: '¿Has mandado una foto subida de tono (nude) a la persona equivocada por accidente?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-33', text: '¿Has usado a alguien para sacarle celos a tu ex o a otra persona que sí te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-34', text: '¿Alguna vez te has quedado dormido/a durante los besos o el juego previo con alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-35', text: '¿Cuál de tus exes te da más vergüenza admitir que fue tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-36', text: '¿Alguna vez te has enamorado de alguien solo por su físico sabiendo que su personalidad era pésima?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-37', text: '¿Has ocultado a tu pareja actual en tus redes sociales para parecer disponible ante otros?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-38', text: '¿Qué rasgo físico de una persona te quita las ganas de todo al instante por más atractiva que sea?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-39', text: '¿Alguna vez has mentido sobre tu edad o tu estado civil para ligar con alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-40', text: '¿Cuál ha sido la cita más costosa que pagaste y que terminó siendo un desastre total?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-41', text: '¿Has guardado fotos o fotos íntimas de tu ex después de haber terminado la relación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-42', text: '¿Qué es lo más vergonzoso que te ha dicho o hecho un ligue en pleno acto afectivo?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-43', text: '¿Has bloqueado y desbloqueado a la misma persona más de 3 veces en la misma semana por inestabilidad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-44', text: '¿Alguna vez has coqueteado con alguien solo para que te pagara la bebida o la comida?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-45', text: '¿Qué excusa tonta inventaste para no tener intimidad cuando estabas sin ganas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-46', text: '¿Has sentido inseguridad por la cantidad de parejas sexuales que ha tenido tu pareja actual?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-47', text: '¿Alguna vez le has pedido a un amigo/a que te llame de emergencia para escapar de una cita horrible?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-48', text: '¿Qué fetiche o gusto sutil tienes que temes revelar por miedo a que piensen que eres raro/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-49', text: '¿Has besado a alguien en una fiesta y al día siguiente no recordabas ni su nombre ni su cara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-50', text: '¿Qué es lo más lejos que has llegado físicamente con alguien en la primera cita?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-51', text: '¿Alguna vez has revisado el perfil del ex de tu pareja actual para comparar quién es más atractivo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-52', text: '¿Has inventado tener una enfermedad o drama personal para dar lástima a alguien que te interesaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-53', text: '¿Qué es lo que más te molesta de la forma en que besa o abraza tu pareja o último ligue?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-54', text: '¿Alguna vez te has quedado en una relación tóxica únicamente porque el sexo o la atracción era increíble?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-55', text: '¿Has sentido celos enfermizos de la mejor amiga o mejor amigo de tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-56', text: '¿Qué outfit o prenda usas estratégicamente cuando sabes que vas a ver a la persona que te gusta?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-57', text: '¿Has usado apps de citas (Tinder, Bumble, etc.) mientras estabas formalmente en una relación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-58', text: '¿Alguna vez te han sorprendido tus padres o familiares coqueteando o besándote con alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-59', text: '¿Cuál es la mentira más absurda que te creíste de un ex porque estabas cegado/a por amor?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-60', text: '¿Has mandado indirectas explícitas en historias de Instagram o WhatsApp dirigidas a una persona específica?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-61', text: '¿Qué es lo más desesperado que has hecho para que alguien te responda un mensaje borrado o ignorado?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-62', text: '¿Alguna vez has tenido un "casi algo" que te doliera más que el fin de una relación formal?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-63', text: '¿Has fingido que te gustaba la misma música, pasatiempos o deportes que a tu ligue solo para agradarle?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-64', text: '¿Qué rasgo de tu personalidad sientes que ha ahuyentado a más personas interesadas en ti?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-65', text: '¿Alguna vez has besado a alguien por despecho el mismo día o semana que terminaste con tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-66', text: '¿Cuál es el secreto de pareja que jamás le contarías a tus mejores amigos por lealtad o vergüenza?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-67', text: '¿Has sentido rabia cuando te enteraste de que tu ex empezó a salir con alguien más guapo/a que tú?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-68', text: '¿Qué es lo más feo que has pensado del cuerpo o físico de alguien mientras te besaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-69', text: '¿Alguna vez has fingido estar borracho/a para atreverte a besar o declarar tus intenciones a alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-70', text: '¿Has tenido una relación secreta o escondida porque te daba vergüenza lo que dijera tu entorno?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-71', text: '¿Qué es lo más vergonzoso que te ha pillado haciendo la persona que te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-72', text: '¿Alguna vez has prometido cosas que sabías que no ibas a cumplir con tal de conseguir una segunda cita?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-73', text: '¿Qué regalo de un ex conservas todavía porque te gusta demasiado aunque tu pareja actual no lo sepa?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-74', text: '¿Has sentido arrepentimiento inmediato justo después de haberte besado o acostado con alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-75', text: '¿Alguna vez te has creado una cuenta falsa para stalkear a un ligue, ex o rival amoroso?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-76', text: '¿Qué comentario sobre tu desempeño o aspecto en la intimidad te destruyó la autoestima por un tiempo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-77', text: '¿Has continuado hablando con un ex a espaldas de tu pareja actual bajo la excusa de "solo somos amigos"?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-78', text: '¿Qué es lo más ridículo que has buscado en Google sobre cómo gustarle a alguien o cómo besar mejor?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-79', text: '¿Alguna vez te has sentido rechazado/a sexualmente por tu pareja y cómo afectó tu ego?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-80', text: '¿Cuál es la mentira más común que le dices a las personas cuando no quieres nada serio con ellas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-81', text: '¿Has fingido tener dinero o un estilo de vida más elevado para impresionar a un ligue?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-82', text: '¿Qué canción de desamor has cantado a todo pulmón pensando en alguien de esta sala o de tu pasado reciente?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-83', text: '¿Alguna vez has sentido envidia del atractivo o pegue que tiene tu mejor amigo/a con los demás?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-84', text: '¿Qué es lo más atrevido que has hecho estando a solas con alguien en un auto?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-85', text: '¿Has criticado la apariencia o forma de vestir del ligue de un amigo/a por pura envidia o celos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-86', text: '¿Alguna vez has tenido un romance de fiesta que prometió amor eterno y nunca más se volvieron a hablar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-87', text: '¿Qué es lo más sumiso o humillante que has aceptado hacer por amor o por no perder a alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-88', text: '¿Has comparado el tamaño, cuerpo o físico de tu pareja con contenido para adultos que consumes?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-89', text: '¿Alguna vez le has mandado un mensaje subido de tono a la persona equivocada en medio de la noche?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-90', text: '¿Qué inseguridad sobre tu rendimiento en la cama te quita el sueño antes de estar con alguien nuevo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-91', text: '¿Has sentido tentación real de besar a alguien de tu mismo sexo solo por curiosidad o juego?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-92', text: '¿Qué es lo más infantil que has hecho tras una ruptura amorosa para llamar la atención?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-93', text: '¿Alguna vez te has arrepentido de no haberte lanzado a besar a alguien que te dio todas las señales?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-94', text: '¿Has coqueteado con alguien frente a tu pareja solo para medir su nivel de celos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-95', text: '¿Qué secreto de la vida íntima de tu ex le contaste a tus amigos y juraste guardar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-96', text: '¿Alguna vez has tenido un crush o platónico con el hermano o hermana de un amigo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-97', text: '¿Qué excusa has usado para irte de la casa de alguien justo después de tener intimidad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-98', text: '¿Has dicho que estabas ocupado/a para no salir con alguien feo/a pero saliste con otra persona esa misma noche?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-99', text: '¿Alguna vez has sentido que alguien te gustaba mucho hasta que lo viste comer, bailar o hablar mal?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-100', text: '¿Quién de las personas presentes en este juego te parece la más atractiva físicamente?', level: 2, genderTarget: 'all' },

  // ——— Nivel 3: Se 😈 ———
  { id: 'q-l3-01', text: '¿Qué prefieres: que tu mamá te encuentre masturbándote o encontrar a tu mamá masturbándose?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-02', text: '¿Alguna vez has tenido atracción o pensamientos sexuales hacia un familiar lejano o cercano?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-03', text: 'Si supieras con certeza que nadie nunca se enterará, ¿te acostarías con la pareja de tu mejor amigo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-04', text: '¿Qué es lo más humillante que has tolerado a cambio de sexo o para mantener a alguien a tu lado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-05', text: '¿Alguna vez has tenido relaciones con alguien sabiendo que esa persona tenía pareja comprometida?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-06', text: '¿Te has acostado con alguien a quien considerabas feo/a o desagradable solo por pura desesperación?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-07', text: '¿Alguna vez te has grabado o tomado fotos íntimas comprometedoras y tuviste miedo de que se filtraran?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-08', text: '¿Has felt atracción sexual hacia el padre o la madre de alguno de tus amigos cercanos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-09', text: '¿Te ha producido asco o repulsión el cuerpo de tu pareja durante el acto sexual?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-10', text: '¿Te has acostado con alguien sabiendo que estaba enamorado/a de ti, usándolo/a solo para pasar el rato?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-11', text: '¿Has fantaseado con el/la mejor amigo/a de tu pareja mientras tenías relaciones con tu pareja?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-12', text: 'Si pudieras ver exactamente cuántas personas han tenido fantasías sexuales contigo, ¿crees que el número te subiría el ego o te decepcionaría?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-13', text: 'Si pudieras acostarte con alguien de esta sala sin ninguna consecuencia, ¿a quién elegirías y qué le harías?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-14', text: '¿Alguna vez has grabado o tomado fotos íntimas de alguien sin su consentimiento explícito?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-15', text: '¿Alguna vez te has aprovechado del estado de ebriedad de alguien para conseguir afecto o sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-16', text: '¿Cuál es la fantasía sexual más oscura o retorcida que tienes y que nunca le has contado a nadie?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-17', text: '¿Con quién de los presentes irías a un cuarto oscuro en este momento y qué sería lo primero que harían?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-18', text: '¿Con cuántas personas te has acostado en total y cuántas de ellas consideras que fueron un error tremendo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-19', text: '¿Cuál ha sido el lugar más arriesgado o prohibido donde has tenido relaciones sexuales?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-20', text: '¿Qué es lo más hot y placentero que te han hecho en la cama que jamás olvidarás?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-21', text: '¿Si pasaras tiempo en prisión, tendrías relaciones íntimas con otros presos/as?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-22', text: '¿Por qué diste tu virginidad realmente? ¿Fue por amor o acaso no pudiste aguantar la gana?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-23', text: '¿Has participado en un trío u orgía o lo harías si se te presenta la oportunidad esta noche?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-24', text: '¿Qué postura o acto sexual te dejó físicamente exhausto/a o adolorido/a por días?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-25', text: '¿Alguna vez se te ha roto el preservativo en pleno acto y cómo reaccionaste en ese instante?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-26', text: '¿Has sentido un orgasmo tan fuerte que terminaste llorando o riendo sin control?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-27', text: '¿Cuál es el fetiche más extremo que has probado o que te gustaría que te practicaran?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-28', text: '¿Alguna vez has estado a punto de ser descubierto/a teniendo intimidad en público?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-29', text: '¿Te han pagado o has pagado alguna vez por sexo o por contenido erótico privado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-30', text: '¿Alguna vez has tenido relaciones mientras alguien más dormía en la misma habitación?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-31', text: '¿Qué pensamiento intrusivo o morboso has tenido en plena intimidad que te dio vergüenza de ti mismo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-32', text: '¿Has experimentado sexo bajo el efecto de alguna sustancia o alcohol? ¿Fue mejor o peor?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-33', text: '¿Alguna vez has fingido que te gustaba un juego o fetiche rudo solo para complacer a tu pareja?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-34', text: '¿Cuál ha sido la eyaculación o momento más vergonzoso por falta de control que has tenido?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-35', text: '¿Has usado juguetes sexuales solos o en pareja? ¿Cuál es tu favorito?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-36', text: '¿Te has grabado teniendo relaciones y guardas ese video en una carpeta secreta?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-37', text: 'Si tuvieras que hacer un trío obligatoriamente con dos personas de esta sala, ¿a quiénes elegirías?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-38', text: '¿Has sentido la necesidad irresistible de masturbarte en un lugar público o de trabajo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-39', text: '¿Cuál es el fluido corporal en el sexo que te da más asco o repulsión presenciar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-40', text: '¿Alguna vez has tenido un encuentro íntimo con alguien cuyo nombre no sabías?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-41', text: '¿Has sido infiel físicamente a alguna pareja formal y nunca te descubrieron?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-42', text: '¿Te han atrapado masturbándote en tu casa? ¿Quién fue y cómo reaccionaron?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-43', text: '¿Qué es lo más sucio o explicito que has dicho durante el "dirty talk" en la cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-44', text: '¿Alguna vez te has acostado con alguien por pura venganza hacia otra persona?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-45', text: '¿Has estado con más de una persona en un mismo período de 24 horas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-46', text: '¿Cuál es tu lugar prohibido soñado para tener relaciones sin ser visto/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-47', text: '¿Has probado o te llama la atención el sexo anal? ¿Cómo fue tu experiencia?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-48', text: '¿Qué calificación del 1 al 10 le darías a la mejor persona con la que te has acostado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-49', text: '¿Te has quedado a medias en el sexo porque la otra persona lo hacía insoportablemente mal?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-50', text: '¿Cuál es la mentira más grave que has dicho para acostarte con alguien esa misma noche?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-51', text: '¿Alguna vez has experimentado atracción erótica hacia un compañero/a de trabajo o estudio actual?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-52', text: '¿Has enviado fotos de tus partes íntimas sin que te las pidieran expresamente?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-53', text: '¿Qué disfraz o juego de rol erótico te causa más excitación pensar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-54', text: '¿Alguna vez te has masturbado pensando en la pareja de un amigo/a cercano/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-55', text: '¿Te han dejado marcas evidentes (chupones, rasguños) en el cuerpo que tuviste que ocultar con mentiras?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-56', text: '¿Has tenido sexo en el mar, en una piscina o jacuzzi? ¿Valió la pena?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-57', text: '¿Alguna vez has sentido dolor o molestia intensa durante el acto pero te callaste por no arruinar el momento?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-58', text: '¿Cuál es la práctica íntima que dijiste que jamás harías y terminaste cediendo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-59', text: '¿Te ha gustado alguien considerablemente mayor que tú (más de 15 años de diferencia)?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-60', text: '¿Alguna vez te has sentido usado/a como un simple objeto sexual después de un encuentro?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-61', text: '¿Qué es lo más provocativo o atrevido que llevarías puesto debajo de la ropa en una fiesta como hoy?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-62', text: '¿Has probado ataduras, dominación o sadomasoquismo suave durante la intimidad?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-63', text: '¿Cuál es la razón más ridícula por la que rechazaste tener relaciones cuando ya estaban desnuditos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-64', text: '¿Has sentido ganas de masturbarte inmediatamente después de terminar de tener relaciones con alguien?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-65', text: '¿Alguna vez le has pedido a alguien que cambie su higiene íntima antes de continuar en la cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-66', text: '¿Qué es lo más extremo que has hecho estando a solas en tu vehículo con alguien?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-67', text: '¿Has tenido relaciones sexuales en la casa de los padres de tu pareja mientras ellos estaban allí?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-68', text: '¿Cuál ha sido la fantasía que probaste en la vida real y resultó ser una decepción total?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-69', text: '¿Alguna vez te has masturbado usando objetos cotidianos no diseñados para eso?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-70', text: '¿Has sentido atracción por alguien solo por la forma en que huele su sudor o cuerpo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-71', text: '¿Qué es lo más rápido que has terminado durante un encuentro íntimo y por qué pasó?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-72', text: '¿Alguna vez has llorado después de alcanzar un orgasmo por exceso de emoción o culpa?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-73', text: '¿Te gustaría que tu pareja tuviera un encuentro íntimo con otra persona mientras tú miras?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-74', text: '¿Has mentido diciendo que tomabas anticonceptivos o usando protección sin ponerla realmente?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-75', text: '¿Qué es lo más sucio o atrevido que le has pedido a alguien por nota de voz?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-76', text: '¿Has tenido sexo en un baño público de una discoteca o evento?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-77', text: '¿Qué parte de tu cuerpo te encanta que te besen o muerdan con fuerza durante el sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-78', text: '¿Alguna vez has dicho el nombre de otra persona por equivocación durante el acto íntimo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-79', text: '¿Cuál es la peor lesión o golpe que has sufrido durante una sesión de sexo intensa?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-80', text: '¿Has fingido estar ebrio/a para justificar una locura íntima que querías hacer de verdad?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-81', text: '¿Alguna vez has tenido un orgasmo nocturno mientras dormías y te despertaste en el acto?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-82', text: '¿Qué es lo más arriesgado que has hecho en un avión, autobús o tren de viaje?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-83', text: '¿Te han hecho un baile erótico privado o lo has hecho tú para alguien?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-84', text: '¿Has sentido celos de los juguetes sexuales de tu pareja porque sientes que le dan más placer?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-85', text: '¿Cuál es la frecuencia máxima de relaciones o masturbación que has alcanzado en un solo día?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-86', text: '¿Alguna vez has tenido que parar el sexo porque te dio un calambre o dolor ridículo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-87', text: '¿Te ha gustado alguien de tu mismo sexo hasta el punto de querer tener una experiencia erótica real?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-88', text: '¿Qué es lo más vergonzoso que ha salido de tu boca mientras estabas al borde del orgasmo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-89', text: '¿Has mirado a otra persona a los ojos en una fiesta mientras te masturbabas o te tocaban a escondidas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-90', text: '¿Cuál es el secreto erótico sobre ti que te llevarás a la tumba si nadie de aquí lo descubre hoy?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-91', text: '¿Alguna vez has comprado o usado lencería/ropa interior comestible o temática?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-92', text: '¿Qué es lo más salvaje que le harías a tu crush si te dijera que sí a todo esta noche?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-93', text: '¿Has continuado el acto íntimo aun sabiendo que no tenías ganas, solo por cumplir?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-94', text: '¿Qué sonido o gemido de tu pareja te quita las ganas o te resulta insoportable?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-95', text: '¿Alguna vez te has masturbado en el baño de la casa de un amigo/a durante una reunión?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-96', text: '¿Qué es lo más extremo que has aceptado hacer frente a una cámara web o llamada erótica?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-97', text: '¿Has tenido sexo en un lugar con espejo donde podías ver todo lo que hacían?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-98', text: '¿Qué es lo más picante que has probado con comida (crema, hielo, chocolate) en la cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-99', text: '¿Alguna vez has salido sin ropa interior a la calle a propósito por la adrenalina?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-100', text: '¿Si pudieras pasar una noche de pasión salvaje con cualquier persona presente en esta ronda, a quién elegirías sin pensarlo dos veces?', level: 3, genderTarget: 'all' },
];