import type { Question } from '../types/game';

export const QUESTIONS: Question[] = [
  // ——— Nivel 1: Conociéndonos ———
  { id: 'q-l1-01', text: '¿A quién del grupo le fingirías que te encantó un regalo horrible?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-02', text: '¿Cómo escapaste de la peor cita o salida que has tenido?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-03', text: '¿Qué canción es el soundtrack de tu peor decisión del último año?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-04', text: '¿Qué comida asquerosa o rara te encanta comer a escondidas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-05', text: 'Si tu vida amorosa fuera una película, ¿cuál sería el título?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-06', text: '¿Cuál es tu mayor miedo absurdo que te da pena admitir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-07', text: '¿Cuándo fue la última vez que oliste ropa sucia para ver si te la ponías?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-08', text: '¿Qué es lo más antihigiénico que haces cuando estás solo en casa?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-09', text: '¿Cuándo fue la última vez que te comiste un moco ya de adulto?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-10', text: '¿Cuándo fue la última vez que tuviste un accidente estomacal encima?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-11', text: '¿En qué lugar público te has olido disimuladamente para ver si apestaba?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-12', text: '¿Qué es lo más turbio que has buscado en modo incógnito?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-13', text: '¿Qué revisaste la última vez que esculcaste cosas ajenas por chisme?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-14', text: '¿De qué trabajo o mérito ajeno te adueñaste para quedar bien?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-15', text: '¿Qué rajaste de tu mejor amigo/a a sus espaldas para encajar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-16', text: '¿Qué fue lo último que le robaste a un amigo o familiar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-17', text: '¿A quién de tus conocidos le deseaste en secreto que le fuera mal?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-18', text: '¿Cuál es el secreto más pesado que le ocultas a tus padres?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-19', text: '¿Qué enfermedad inventaste para zafarte de un compromiso?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-20', text: '¿Cuánto dinero ajeno te quedaste sabiendo de quién era?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-21', text: '¿Qué desgracia ajena te dio profunda satisfacción secreta?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-22', text: '¿Qué mentira le sostienes a tu familia que aún no descubren?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-23', text: '¿Qué fue lo más bajo o humillante que hiciste por dinero?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-24', text: '¿A quién le fingiste amistad solo por interés o conveniencia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-25', text: '¿A quién de este grupo sientes que en el fondo no le caes bien?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-26', text: 'Si tuvieras que salvar a tu mascota o a un desconocido, ¿a quién eliges?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-27', text: '¿Qué envidia profunda le tienes a un familiar cercano?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-28', text: '¿Qué es lo más feo que has pensado del aspecto físico de tu mejor amigo/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-29', text: '¿Por qué tomas alcohol realmente: diversión, presión o depresión?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-30', text: '¿Qué defecto tuyo te haría ser un pésimo padre o madre?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-31', text: '¿Cuál es la mentira que más repites a diario para quedar bien?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-32', text: '¿Qué comida defiendes a muerte aunque todos digan que sabe horrible?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-33', text: '¿Cuál ha sido el peor corte de pelo o look que te arruinó la vida?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-34', text: '¿Qué app borrarías de inmediato si te revisaran el celular ahora?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-35', text: '¿Cuál es el chisme más jugoso de tu trabajo o lugar de estudio?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-36', text: '¿Qué serie o contenido basura ves en secreto porque te da vergüenza?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-37', text: '¿Cuál ha sido tu excusa más descarada para llegar tarde?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-38', text: '¿De quién de tus amigos te burlarías primero en un show de comedia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-39', text: '¿Cuál fue tu peor error de moda durante la adolescencia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-40', text: '¿Qué canción ridícula te sabes completa y jamás cantarías en público?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-41', text: '¿Qué regalo horrible recibiste en un intercambio y a quién se lo diste?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-42', text: '¿Qué costumbre extraña haces cuando nadie te está mirando?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-43', text: '¿Cuál es tu manía más rara antes o después de dormir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-44', text: '¿A qué famoso o influencer sigues solo para criticarlo o burlarte?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-45', text: '¿En qué presentación o examen hiciste el peor ridículo de tu vida?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-46', text: '¿Qué compra impulsiva e inútil tienes arrumbada cogiendo polvo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-47', text: '¿Qué teoría conspirativa absurda defiendes como real?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-48', text: '¿Qué frase o muletilla insoportable usas todo el tiempo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-49', text: '¿Qué drama exagerado inventaste para faltar a la escuela o trabajo?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-50', text: '¿Qué accidente con tu ropa o maquillaje te dejó en ridículo público?', level: 1, genderTarget: 'M' },
  { id: 'q-l1-51', text: '¿Qué manía de convivencia no soportas de la gente?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-52', text: '¿A qué persona stalkeas casi a diario en redes sociales?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-53', text: '¿Cuál fue tu obsesión o fanatismo infantil más patético?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-54', text: '¿Qué mentira de tus padres te creíste hasta bien grande?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-55', text: '¿Qué mala costumbre tienes al comer que a otros les da asco?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-56', text: '¿A qué famoso feo te dicen que te pareces y te da rabia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-57', text: '¿Cuál fue el peor consejo que seguiste y arruinó tus planes?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-58', text: '¿Cuál fue tu peor metida de pata en una entrevista de trabajo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-59', text: '¿Qué actividad o plan finges disfrutar solo por encajar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-60', text: '¿A qué superstición tonta le tienes miedo real?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-61', text: '¿Qué objeto ridículo de tu infancia conservas escondido?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-62', text: '¿Qué pésimo consejo amoroso le diste a un amigo y arruinó todo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-63', text: '¿A qué figura pública odias con todo tu ser sin conocerla?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-64', text: '¿Qué bochorno hiciste la última vez que te pasaste de tragos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-65', text: '¿Qué costumbre rara de tu familia creías que era normal en todos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-66', text: '¿Qué choque o estupidez cometiste aprendiendo a manejar?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-67', text: '¿Cuál fue el apodo más humillante que te pusieron de niño?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-68', text: '¿Por qué tontería lloraste desconsoladamente este último mes?', level: 1, genderTarget: 'M' },
  { id: 'q-l1-69', text: '¿Qué desastre provocaste en una excursión o paseo escolar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-70', text: '¿Qué mezcla asquerosa de comida te preparas a escondidas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-71', text: '¿Qué mensaje comprometedor mandaste al grupo equivocado?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-72', text: '¿Cuál ha sido tu peor desastre intentando cocinar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-73', text: '¿Qué broma pesada hiciste que se salió de control?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-74', text: '¿Qué rompiste por descuido y culpaste a alguien inocente?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-75', text: '¿Cómo actuaste tu peor fingida de enfermedad para faltar a algo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-76', text: '¿Qué sueño absurdo o bizarro recuerdas como si fuera real?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-77', text: '¿Por qué tontería dejaste de hablarle a tu mejor amigo/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-78', text: '¿Qué es lo más asqueroso que tienes escondido en tu habitación?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-79', text: '¿Qué ridículo hiciste borracho en una pista de baile o karaoke?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-80', text: '¿Qué costumbre de viejo tienes a tu edad?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-81', text: '¿Qué mentira de niño sigues sosteniendo por orgullo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-82', text: '¿Qué logro insignificante presumes como si fueras un genio?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-83', text: '¿Qué drama armaste en un probador de ropa por no entrar en una talla?', level: 1, genderTarget: 'M' },
  { id: 'q-l1-84', text: '¿Cuál ha sido tu foto de perfil más cringe de Facebook o Instagram?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-85', text: '¿Qué oso tremendo pasaste en el transporte público o en la calle?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-86', text: '¿Qué exigencia ridícula haces cuando vas a un restaurante?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-87', text: '¿Qué apodo denigrante le tenías en secreto a tu jefe o profesor?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-88', text: '¿Qué tontería haces para disimular cuando estás solo y aburrido?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-89', text: '¿Qué excusa barata pusiste para dejar en visto a alguien por días?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-90', text: '¿Qué gesto se te escapa cuando alguien que odias te habla?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-91', text: '¿Qué tontería peligrosa hiciste solo por presión de tus amigos?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-92', text: '¿Qué canción vergonzosa es la más escuchada en tu Spotify?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-93', text: '¿Qué complejo físico absurdo te obsesiona cuando sales a la calle?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-94', text: '¿Qué grito o reacción ridícula tuviste la última vez que te asustaron?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-95', text: '¿Qué humillación aceptaste para no perder una apuesta con amigos?', level: 1, genderTarget: 'H' },
  { id: 'q-l1-96', text: '¿Qué maniobra absurda hiciste para esquivar a un conocido en la calle?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-97', text: '¿Qué momento vergonzoso viviste con un médico o dentista?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-98', text: '¿Qué inventaste cuando te saludaron efusivamente y no sabías su nombre?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-99', text: '¿Qué tontería carísima compraste solo por emoción y nunca usaste?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-100', text: 'Si revisas 5 minutos el celular de alguien aquí presente, ¿a quién eliges?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-101', text: '¿Qué complejo de tu infancia o adolescencia te sigue atormentando frente al espejo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-102', text: '¿Qué trauma o herida te dejaron tus padres que todavía no logras perdonarles?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-103', text: '¿En qué momento sentiste que eras una decepción total para tu familia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-104', text: '¿Qué mentira sobre tu felicidad o éxito le vendes a tus amigos en redes sociales?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-105', text: '¿Cuándo fue la última vez que lloraste solo en tu habitación sintiéndote completamente vacío/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-106', text: '¿Qué parte de tu personalidad finges todos los días para no quedarte sin amigos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-107', text: '¿Qué fracaso académico o laboral te hizo sentir que no servías para nada?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-108', text: '¿Qué comentario cruel sobre tu físico te marcó para siempre?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-109', text: '¿A quién de tus amigos le tienes una envidia secreta que te da vergüenza admitir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-110', text: '¿Qué hábito destructivo tienes cuando te gana la ansiedad o la depresión?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-111', text: '¿Por qué sientes que eres el/la más inseguro/a de este grupo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-112', text: '¿Qué secreto familiar vergonzoso ocultas por miedo a lo que digan los demás?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-113', text: '¿Cuándo fue la última vez que fingiste estar bien solo para que nadie te preguntara nada?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-114', text: '¿Qué error del pasado no te deja dormir tranquilo por las noches?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-115', text: '¿Qué defecto físico odias tanto que harías cualquier cosa por cambiártelo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-116', text: '¿Por qué sientes que a la gente le cuesta encariñarse o quedarse contigo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-117', text: '¿Qué vicio o mala costumbre mantienes oculto de todos tus conocidos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-118', text: '¿En qué situación sentiste que nadie en el mundo se preocupaba realmente por ti?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-119', text: '¿Qué injusticia cometiste contra alguien inocente y nunca pediste perdón?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-120', text: '¿Qué talento o sueño abandonaste por miedo al fracaso o a las burlas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-121', text: '¿A quién le guardas un rencor tóxico que sabes que te está envenenando?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-122', text: '¿Qué crítica de tus padres te destruyó la autoestima cuando eras más joven?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-123', text: '¿Qué haces a solas cuando sientes que la soledad te está aplastando?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-124', text: '¿Qué mentira sobre tu dinero o situación económica dices para no pasar vergüenza?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-125', text: '¿Cuál es el miedo más profundo que tienes sobre tu futuro?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-126', text: '¿Qué amistad rompiste por puro orgullo sabiendo que la culpa era tuya?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-127', text: '¿Qué pensamiento negativo sobre ti mismo se repite en tu cabeza todos los días?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-128', text: '¿En qué momento tocaste fondo emocional y quién te dejó solo/a?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-129', text: '¿Qué rasgo que heredaste de tus padres odias ver en ti?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-130', text: '¿Por qué sientes que nunca eres suficiente para las personas que quieres?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-131', text: '¿Qué sustancia o exceso usas como escape cuando no soportas tu realidad?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-132', text: '¿Qué promesa que te hiciste a ti mismo/a rompiste de la forma más mediocre?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-133', text: '¿Qué evento familiar arruinaste por tu mal carácter o inmadurez?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-134', text: '¿De qué te arrepientes de no haberle dicho a alguien antes de que se fuera de tu vida?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-135', text: '¿Qué sientes que estás fingiendo en tu vida actual para no decepcionar a otros?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-136', text: '¿Qué golpe de realidad te hizo madurar de golpe a las malas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-137', text: '¿Por qué te da tanto pánico quedarte solo/a en la vida?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-138', text: '¿Qué logro ajeno de un amigo te dio rabia en lugar de alegría?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-139', text: '¿Cuál fue la peor humillación que soportaste en el colegio o escuela?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-140', text: '¿Qué rechazo social te dolió tanto que te cambió la forma de ser?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-141', text: '¿Qué hábito higiénico o de cuidado personal descuidas cuando caes en depresión?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-142', text: '¿Qué es lo más egoísta que has hecho pensando únicamente en tu bienestar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-143', text: '¿Por qué sientes que nadie aquí conoce tu verdadera personalidad?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-144', text: '¿Qué inseguridad sobre tu inteligencia te hace dudar antes de opinar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-145', text: '¿Qué fue lo más triste que hiciste para intentar encajar en un grupo que te ignoraba?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-146', text: '¿Qué discusión con tus padres terminó en gritos y lágrimas que jamás olvidarás?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-147', text: '¿Qué recuerdo de tu infancia te produce un nudo en la garganta cada vez que vuelve?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-148', text: '¿Por qué te saboteas a ti mismo/a cada vez que las cosas te empiezan a ir bien?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-149', text: '¿Qué traición de un supuesto mejor amigo te dejó con desconfianza crónica?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-150', text: 'Si tuvieras que confesarle una verdad dolorosa a alguien de este grupo ahora mismo, ¿a quién sería?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-151', text: '¿Qué elogio finges creerte cuando en el fondo sabes que no lo mereces?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-152', text: '¿En qué aspecto de tu vida sientes que te estás quedando atrás respecto a tus amigos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-153', text: '¿Qué mentira piadosa le dijiste a tu mamá para que no llorara por ti?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-154', text: '¿Qué pensamiento cruel sobre la inteligencia de tus compañeros de clase o trabajo te guardas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-155', text: '¿Cuándo fue la última vez que sentiste que estorbabas en un grupo de personas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-156', text: '¿Qué parte de tu cuerpo escondes siempre en las fotos grupales?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-157', text: '¿Qué decepción con un profesor o figura de autoridad te quitó las ganas de esforzarte?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-158', text: '¿Qué miedo absurdo a madurar o asumir responsabilidades no te deja avanzar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-159', text: '¿Por qué te da tanta vergüenza invitar a tus amigos a tu casa?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-160', text: '¿Qué es lo más patético que has buscado en internet sobre cómo tener amigos o caer bien?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-161', text: '¿A quién de tu familia no soportas ver en navidades o reuniones y por qué?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-162', text: '¿Qué complejo con tu voz o forma de hablar te hace quedarte callado/a en público?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-163', text: '¿Qué promesa importante le hiciste a tus padres y sabías que no ibas a cumplir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-164', text: '¿En qué momento sentiste que no encajabas ni en tu propia familia?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-165', text: '¿Qué crítica a tu forma de vestir te dolió tanto que botaste esa ropa?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-166', text: '¿Por qué finges tener un humor de hierro cuando cualquier broma pesada te hiere?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-167', text: '¿Qué derrota personal te dolió tanto que preferiste inventar que no te importaba?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-168', text: '¿Qué obsesión extraña con tu aspecto revisas diez veces antes de cruzar la puerta?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-169', text: '¿A quién consideras el eslabón más débil o hipócrita de tu círculo de amigos?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-170', text: '¿Qué hábito sucio o descuidado en tu casa te daría vergüenza mortal que descubrieran?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-171', text: '¿Qué oportunidad única en tu vida dejaste escapar por puro miedo o pereza?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-172', text: '¿Por qué sientes que nadie en este grupo te elegiría como su prioridad número uno?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-173', text: '¿Qué pensamiento egoísta se te cruzó cuando un amigo te pidió un favor urgente?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-174', text: '¿Qué frase hiriente que te dijeron de niño aún resuena en tu cabeza de adulto?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-175', text: '¿Qué mentira sobre tu carrera o trabajo sostienes para que no te tengan lástima?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-176', text: '¿Por qué sientes pánico cada vez que tienes que hablar en público o defender tu punto?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-177', text: '¿Qué recuerdo escolar te da ganas de meter la cabeza bajo tierra de la vergüenza?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-178', text: '¿A qué persona de tu pasado no has podido perdonar por humillarte frente a otros?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-179', text: '¿Qué carencia económica de tu infancia intentas compensar gastando de más hoy?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-180', text: '¿Por qué te comparas compulsivamente con la vida perfecta de desconocidos en redes?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-181', text: '¿Qué defecto de tu carácter sabes que aleja a las personas que de verdad te quieren?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-182', text: '¿Qué es lo más falso que has dicho en un funeral o momento triste solo por cumplir?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-183', text: '¿En qué situación sentiste que tu presencia sobraba completamente en una fiesta?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-184', text: '¿Qué actitud tóxica tienes cuando alguien te supera en algo que creías dominar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-185', text: '¿Qué secreto médico o de salud mental le ocultas a tus personas cercanas?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-186', text: '¿Por qué sientes que si la gente te conociera al 100% saldría corriendo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-187', text: '¿Qué dinero prestado a un amigo diste por perdido con tal de no confrontarlo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-188', text: '¿Qué frustración con tu estatura, peso o complexión te amarga los días?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-189', text: '¿A quién le diste la espalda cuando más necesitaba apoyo por evitarte un problema?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-190', text: '¿Qué drama innecesario armaste solo porque no estabas siendo el centro de atención?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-191', text: '¿Qué vicio menor (juegos, compras, comida) te hace sentir culpable cada vez que caes?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-192', text: '¿Por qué te cuesta tanto pedir ayuda cuando estás colapsando emocionalmente?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-193', text: '¿Qué mentira sobre tu infancia inventaste para que tus compañeros te vieran genial?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-194', text: '¿Qué pensamiento oscuro has tenido sobre desaparecer y empezar de cero en otro país?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-195', text: '¿Qué actitud de tus padres juraste no repetir jamás y hoy te descubres haciendo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-196', text: '¿En qué examen o prueba hiciste la trampa más descarada para no reprobar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-197', text: '¿Por qué sientes que siempre tienes que ser el chistoso o el servicial para ser aceptado?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-198', text: '¿Qué insulto o apodo que te dijeron en la adolescencia todavía te duele recordar?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-199', text: '¿A quién de tus conocidos eliminarías de tu vida con un botón mágico sin dudarlo?', level: 1, genderTarget: 'all' },
  { id: 'q-l1-200', text: '¿Qué es lo más honesto y doloroso que tendrías que admitir sobre tu vida actual?', level: 1, genderTarget: 'all' },

  // ——— Nivel 2: Juego previo ———
  { id: 'q-l2-01', text: '¿Qué ex te dio la mejor noche de tu vida y qué no ha podido superar tu pareja actual?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-02', text: '¿Qué ex te volvía más loco en la cama y qué le falta a tu novia actual para igualarla?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-03', text: '¿Qué fue lo más turbio que le descubriste a tu pareja al revisarle el celular?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-04', text: '¿Por qué fingiste tu último orgasmo y qué cara pusiste para que te creyeran?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-05', text: '¿Qué defecto higiénico o mal olor te mató las ganas con alguien que te encantaba?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-06', text: '¿Qué indirecta o avance le tiraste a la pareja de un amigo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-07', text: '¿Qué mentira exagerada dijiste sobre tu experiencia en la cama?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-08', text: '¿A quién botaste de una cita solo porque en persona se veía feo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-09', text: '¿Qué buscabas la última vez que stalkeaste obsesivamente a tu ex?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-10', text: '¿En qué supera tu ex a tu pareja actual en la intimidad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-11', text: '¿Cuándo te dio vergüenza que te vieran en público con tu pareja o ligue?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-12', text: '¿Por qué conveniencia económica o estatus saliste con alguien que no te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-13', text: '¿Cómo disimulaste el pedo o ruido raro que se te escapó en pleno acto?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-14', text: '¿Cuánto peso tendría que subir tu pareja para que pierdas el interés?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-15', text: '¿Qué chantaje emocional le montaste a tu ex para que no te dejara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-16', text: '¿Qué es lo peor que dijiste de la familia de tu pareja a sus espaldas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-17', text: '¿A quién le hiciste ghosting cobardemente por no dar la cara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-18', text: '¿Por qué seguiste acostándote con alguien a quien ya no querías?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-19', text: '¿Cuál fue tu mentira más descarada para llevarte a una mujer a la cama?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-20', text: '¿Qué mensaje caliente escribiste y borraste por miedo a parecer desesperada?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-21', text: '¿Qué mentira dijiste sobre tus gustos solo para comerte a besos a alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-22', text: '¿Qué parte de tu cuerpo intentas tapar o disimular al desnudarte?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-23', text: '¿Qué chat comprometedor borraste de emergencia por miedo a que lo vieran?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-24', text: '¿Qué humillación hiciste por llamar la atención de quien te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-25', text: '¿Qué fantasía tuviste con un jefe o profesor estando en pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-26', text: '¿Qué pensamiento o sueño te hizo dudar de tu orientación sexual?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-27', text: '¿Qué jugada sucia le hiciste a tu ex por pura venganza?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-28', text: '¿Qué te detuvo en el último segundo antes de ser infiel?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-29', text: '¿A quién le dijiste "te amo" por compromiso y sin sentirlo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-30', text: '¿Cuál fue tu ataque de celos más tóxico y desquiciado?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-31', text: '¿A quién le diste el beso más asqueroso y qué tenía de malo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-32', text: '¿A quién le enviaste un nude o foto provocativa por error?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-33', text: '¿Con quién saliste solo para darle celos y rabia a tu ex?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-34', text: '¿Por qué te quedaste dormido/a en pleno beso o previa con alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-35', text: '¿Cuál de tus exes te da vergüenza pública admitir que te comiste?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-36', text: '¿Con qué persona insoportable estuviste solo porque estaba buenísima?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-37', text: '¿Por qué ocultaste a tu pareja en redes sociales para parecer soltero/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-38', text: '¿Qué defecto físico o higiénico te baja la calentura de inmediato?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-39', text: '¿Qué mentira sobre tu edad o estado civil dijiste para ligar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-40', text: '¿Cuánto gastaste en una cita cara que terminó en una decepción total?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-41', text: '¿Qué fotos íntimas de tu ex sigues guardando en tu celular?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-42', text: '¿Qué frase ridícula o matapasiones te dijo un ligue en plena calentura?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-43', text: '¿A quién bloqueaste y desbloqueaste mil veces por no saber soltar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-44', text: '¿A quién coqueteaste solo para que te pagara la cuenta o la fiesta?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-45', text: '¿Qué excusa falsa inventaste para no tener sexo esa noche?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-46', text: '¿Qué número de parejas sexuales de tu pareja te causó celos o inseguridad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-47', text: '¿Qué código de rescate usaste con un amigo para huir de una cita pésima?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-48', text: '¿Qué gusto o morbo íntimo ocultas por miedo a que te juzguen?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-49', text: '¿A quién besaste borracho en una fiesta y ni recuerdas cómo se llamaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-50', text: '¿Qué fue lo más caliente que hiciste en una primera cita?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-51', text: '¿Qué le criticaste al ex de tu pareja actual para sentirte superior?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-52', text: '¿Qué drama o enfermedad inventaste para dar lástima a quien te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-53', text: '¿Qué es lo que peor hace tu pareja o último ligue al besar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-54', text: '¿Por qué te quedaste meses en una relación tóxica donde el sexo era lo único bueno?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-55', text: '¿Qué sospechas tóxicas tienes sobre el/la mejor amigo/a de tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-56', text: '¿Qué ropa provocativa te pones cuando sabes que te vas a cruzar con tu crush?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-57', text: '¿Qué app de citas tenías oculta en tu teléfono estando de novio/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-58', text: '¿Qué estaban haciendo cuando tus padres los pillaron a punto del acto?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-59', text: '¿Qué mentira absurda le creíste a tu ex por estar ciegamente enamorado/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-60', text: '¿A quién le tiraste una indirecta caliente en tus historias de Instagram?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-61', text: '¿Qué humillación hiciste para que te respondieran un mensaje ignorado?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-62', text: '¿Qué "casi algo" te dolió más perder que a tu relación formal más larga?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-63', text: '¿Qué gustos o música fingiste amar solo para gustarle a alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-64', text: '¿Qué defecto tuyo arruina todas tus relaciones amorosas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-65', text: '¿Con quién te besaste por puro despecho el mismo día que terminaste?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-66', text: '¿Qué secreto íntimo de tu pareja no le contarías ni a tus amigos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-67', text: '¿Qué sentiste al ver que tu ex se consiguió a alguien más atractivo/a que tú?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-68', text: '¿Qué defecto físico le viste a alguien en pleno beso que te dio asco?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-69', text: '¿Por qué fingiste estar más borracho/a para atreverte a besar a alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-70', text: '¿A quién mantuviste como relación secreta porque te daba pena mostrarlo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-71', text: '¿En qué situación bochornosa te pilló la persona que te gustaba?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-72', text: '¿Qué promesa falsa hiciste con tal de conseguir una segunda cita?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-73', text: '¿Qué regalo de tu ex conservas a escondidas de tu pareja actual?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-74', text: '¿Por qué te arrepentiste de inmediato tras acostarte con alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-75', text: '¿Qué perfil falso usaste para espiar a tu ligue o a su ex?', level: 2, genderTarget: 'M' },
  { id: 'q-l2-76', text: '¿Qué crítica a tu cuerpo en la intimidad te dolió en el alma?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-77', text: '¿Qué conversaciones secretas mantienes con tu ex diciendo que son "amigos"?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-78', text: '¿Qué técnica ridícula buscaste en Google para ser mejor en la cama?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-79', text: '¿Cómo reaccionaste cuando te rechazaron en la cama estando ya calientes?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-80', text: '¿Qué frase usas para ilusionar y salir corriendo cuando no quieres nada serio?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-81', text: '¿Qué lujos o dinero presumiste tener para impresionar a una mujer?', level: 2, genderTarget: 'H' },
  { id: 'q-l2-82', text: '¿Qué canción de despecho cantas a gritos pensando en tu ex?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-83', text: '¿Qué envidia le tienes a tu amigo/a por tener más éxito con las citas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-84', text: '¿Qué fue lo más caliente que hiciste a oscuras dentro de un carro?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-85', text: '¿Por qué criticaste la apariencia del nuevo ligue de tu amigo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-86', text: '¿Qué romance apasionado de una noche prometió amor y nunca más apareció?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-87', text: '¿Qué humillación aceptaste soportar para que tu ex no te dejara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-88', text: '¿Qué le comparaste al cuerpo de tu pareja con el porno que ves?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-89', text: '¿Qué mensaje caliente le mandaste a la persona equivocada a las 3 AM?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-90', text: '¿Qué inseguridad sobre tu tamaño o técnica te quita el sueño antes de debutar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-91', text: '¿Qué persona de tu mismo sexo te hizo dudar de tus gustos por un segundo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-92', text: '¿Qué berrinche o show tóxico hiciste tras una ruptura amorosa?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-93', text: '¿Con quién perdiste la oportunidad de acostarte por cobarde?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-94', text: '¿A quién le coqueteaste en la cara a tu pareja para darle celos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-95', text: '¿Qué secreto íntimo y prohibido de tu ex le contaste a todo el mundo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-96', text: '¿Qué atracción prohibida tuviste con el hermano/a de tu amigo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-97', text: '¿Qué excusa patética diste para salir huyendo de la cama tras el acto?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-98', text: '¿A quién dejaste plantado/a por irte con alguien más atractivo/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-99', text: '¿Qué detalle desagradable te mató el amor por completo hacia alguien?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-100', text: '¿A quién de los presentes te comerías a besos si no hubiera consecuencias?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-101', text: '¿Qué droga o sustancia probaste en una fiesta y terminaste teniendo un mal viaje espantoso?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-102', text: '¿Qué relación tóxica te destruyó psicológicamente y cuánto tardaste en salir de ahí?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-103', text: '¿A quién usaste como clavo para olvidar a tu ex sabiendo que le romperías el corazón?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-104', text: '¿Qué mensaje desesperado le enviaste borracho/a a tu ex rogando que volviera?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-105', text: '¿En qué mentira fuiste descubierto con las manos en la masa por tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-106', text: '¿Qué sustancia consumiste que te hizo hacer el mayor ridículo de tu vida ante conocidos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-107', text: '¿Qué infidelidad emocional cometiste mientras dormías al lado de tu pareja formal?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-108', text: '¿Qué te dolió más: que te engañaran o enterarte de con quién te engañaron?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-109', text: '¿Por qué continuaste con alguien a quien ya no amabas solo por miedo a la soledad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-110', text: '¿Qué fue lo más bajo que hiciste para vengarte de alguien que te rechazó?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-111', text: '¿Qué conversación secreta mantuviste con alguien prohibido sabiendo que cruzabas la línea?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-112', text: '¿Qué exceso de alcohol o drogas te borró la memoria y al despertar sentiste puro pánico?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-113', text: '¿A qué ex le destruiste la salud mental con tus celos y manipulación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-114', text: '¿Qué secreto de tu pasado le ocultaste a tu pareja actual porque sabes que te terminaría?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-115', text: '¿Por qué te metiste en una relación sabiendo desde el día uno que no iba a funcionar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-116', text: '¿Qué mentira sobre tus sentimientos le dijiste a alguien para tener sexo fácil?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-117', text: '¿Con quién compartiste drogas o sustancias a espaldas de todo tu círculo social?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-118', text: '¿Qué trauma de una relación pasada proyectas injustamente sobre tus ligues actuales?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-119', text: '¿Qué humillación soportaste por una persona que no daba un centavo por ti?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-120', text: '¿A quién le arruinaste la fiesta o salida nocturna por culpa de una borrachera depresiva?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-121', text: '¿Qué pensamiento destructivo tuviste al ver a tu ex feliz con otra persona?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-122', text: '¿Qué te hizo sentir más usado/a emocionalmente en una relación de pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-123', text: '¿Por qué fingiste un ataque de celos o drama solo para llamar la atención de tu ligue?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-124', text: '¿Qué sustancia tomaste antes de una cita para calmar tus nervios e inseguridades?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-125', text: '¿Qué fue lo más falso que le prometiste a una pareja sabiendo que no lo cumplirías?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-126', text: '¿A quién le rogaste de rodillas o llorando para que no te dejara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-127', text: '¿Qué inseguridad corporal te impidió disfrutar del sexo con alguien que te gustaba mucho?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-128', text: '¿Qué fue lo más tóxico que le revisaste a tu pareja sin que se diera cuenta jamás?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-129', text: '¿Por qué saboteaste una relación sana con una persona buena solo porque te aburría la paz?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-130', text: '¿Qué estupidez hiciste bajo los efectos de sustancias de la que te avergüenzas profundamente?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-131', text: '¿A quién le diste falsas esperanzas durante meses solo para subirte el ego?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-132', text: '¿Qué secreto de alcoba de un amigo/a revelaste a otros para generar chisme?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-133', text: '¿Qué traición amorosa cometiste con alguien del círculo cercano de tu ex?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-134', text: '¿Por qué te acostaste con alguien sabiendo que al día siguiente te ibas a sentir como basura?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-135', text: '¿Qué es lo más patético que hiciste para intentar coincidir por casualidad con tu crush?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-136', text: '¿Qué droga o alcohol mezclaste que casi te manda al hospital o te hizo desmayarte?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-137', text: '¿A quién bloqueaste de tu vida sin darle ninguna explicación por pura cobardía?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-138', text: '¿Qué comparación destructiva hiciste entre tu cuerpo y el del ligue de tu ex?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-139', text: '¿Qué mentira le sostuviste a tu pareja para salir de fiesta con otras personas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-140', text: '¿Qué vacío emocional intentas llenar cambiando de ligue cada fin de semana?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-141', text: '¿Por qué te quedaste callado/a cuando viste a un amigo siendo infiel a su pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-142', text: '¿Qué fue lo más hiriente que le gritaste a alguien que te amaba de verdad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-143', text: '¿Qué miedo a ser vulnerable te impide tener una relación seria y madura?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-144', text: '¿A quién le enviaste indirectas destructivas por redes esperando ver su reacción?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-145', text: '¿Qué error imperdonable cometiste en una borrachera que cambió la dinámica con tus amigos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-146', text: '¿Por qué toleraste que tu pareja te minimizara o te hiciera sentir insuficiente?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-147', text: '¿Qué fue lo más manipulador que hiciste fingiendo estar triste para conseguir afecto?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-148', text: '¿A qué persona nunca debiste haber besado y hoy te da asco recordar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-149', text: '¿Qué secreto oscuro de tu vida amorosa enterraste para siempre para no ser juzgado/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-150', text: '¿A quién de los presentes lastimarías sin querer si se llegara a enamorar de ti?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-151', text: '¿Qué borrachera violenta o fuera de control te costó una amistad de años?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-152', text: '¿Qué mentira piadosa sobre el sexo le dijiste a tu pareja para no herir su ego?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-153', text: '¿A quién utilizaste para poner celoso a tu ex en una fiesta donde estaban todos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-154', text: '¿Qué promesa romántica vacía le hiciste a alguien en plena noche de tragos y drogas?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-155', text: '¿Qué conversación comprometedora borraste justo antes de prestarle tu celular a tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-156', text: '¿Por qué perdonaste una infidelidad evidente sabiendo que te iban a volver a engañar?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-157', text: '¿Qué papelón bochornoso hiciste afuera de la casa de tu ex a altas horas de la madrugada?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-158', text: '¿Qué sustancia o mezcla prohibida tomaste en una discoteca que te dejó tirado/a en un baño?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-159', text: '¿Qué mensaje tóxico enviaste desde una cuenta secundaria para vigilar a tu ligue?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-160', text: '¿Por qué dejaste que una persona que no te gustaba te besara toda la noche?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-161', text: '¿Qué foto íntima tuya enviaste a alguien que apenas conocías por pura necesidad de validación?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-162', text: '¿A quién le hiciste creer que estaban enamorados solo para no dormir solo/a ese fin de semana?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-163', text: '¿Qué trauma sexual o bloqueo íntimo tienes que no te atreves a contarle a tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-164', text: '¿Qué fue lo más humillante que hiciste para intentar recuperar a alguien que ya tenía otra pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-165', text: '¿Por qué te metiste en una relación de rebote sabiendo que aún llorabas por tu ex?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-166', text: '¿Qué crítica despiadada sobre el desempeño en la cama de un ex compartiste con tus amigos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-167', text: '¿Qué excusa patética diste al día siguiente para no volver a hablarle a quien te llevaste a la cama?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-168', text: '¿Qué vacío afectivo intentaste tapar consumiendo alcohol o drogas hasta perder el conocimiento?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-169', text: '¿A qué amigo/a le robaste un ligue o interés amoroso por pura envidia competitiva?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-170', text: '¿Qué detalle morboso de la vida sexual de tus amigos te enteraste por accidente y te guardaste?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-171', text: '¿Por qué te quedaste meses aguantando malos tratos con tal de no volver a estar soltero/a?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-172', text: '¿Qué regalo costoso le aceptaste a alguien sabiendo que nunca le ibas a dar una oportunidad?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-173', text: '¿Qué drama armado en público protagonizaste con tu pareja en medio de una fiesta?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-174', text: '¿Qué sustancia usaste para poder desinhibirte y tener intimidad con alguien que te daba vergüenza?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-175', text: '¿A quién le clavaste el visto después de que te abrió su corazón con un mensaje largo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-176', text: '¿Qué sospecha de infidelidad confirmaste revisando pertenencias privadas sin permiso?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-177', text: '¿Por qué te dio asco besar a alguien justo después de que terminó la calentura?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-178', text: '¿Qué mentira sobre tu número de parejas sexuales dijiste para que no te juzgaran mal?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-179', text: '¿Qué amigo/a de tu pareja te parece tan irresistible que evitas mirarlo/a a los ojos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-180', text: '¿Qué viaje o salida arruinaste por armarle una escena de celos sin sentido a tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-181', text: '¿A qué ex sigues buscando cuando te sientes solo/a y vulnerable a las 2 de la mañana?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-182', text: '¿Qué es lo más manipulador que dijiste para que tu pareja se sintiera culpable de tu propio error?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-183', text: '¿Qué noche de fiesta se te salió de control al punto de despertar en un lugar peligroso?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-184', text: '¿Por qué mantienes en tu vida a personas que sabes que tienen intenciones de acostarse contigo?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-185', text: '¿Qué confesión de amor no correspondida te dio más lástima que ternura?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-186', text: '¿Qué defecto íntimo de tu pareja te desmotiva por completo pero jamás se lo dirás a la cara?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-187', text: '¿A quién besaste en una fiesta solo para vengarte de un desplante de la noche anterior?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-188', text: '¿Qué fetiche suave o juego de pareja te causó vergüenza ajena cuando te lo propusieron?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-189', text: '¿Por qué aceptaste salir con alguien feo/a únicamente porque tenía auto o dinero?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-190', text: '¿Qué indirecta venenosa publicaste en redes tras una pelea con tu pareja?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-191', text: '¿Qué sustancia o alcohol te transformó en una persona insoportable y agresiva ante tus amigos?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-192', text: '¿A qué casi-algo le reclamaste fidelidad sabiendo que no tenían ningún título formal?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-193', text: '¿Qué recuerdo apasionado con un ex revives en tu mente cuando tu relación actual está aburrida?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-194', text: '¿Por qué fingiste que te sentías mal para escapar de una pijamada o cita incómoda?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-195', text: '¿Qué chat caliente mantienes archivado o bloqueado con contraseña en tu celular?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-196', text: '¿A quién de tus amigos le tendrías celos si empezara a salir con tu crush platónico?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-197', text: '¿Qué mentira dijiste sobre tu estado sentimental para ligar en una fiesta?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-198', text: '¿Qué humillación en redes sociales te hizo pasar tu pareja o un ligue tóxico?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-199', text: '¿Por qué te aferraste a alguien que desde el primer día te dejó claro que solo te quería para un rato?', level: 2, genderTarget: 'all' },
  { id: 'q-l2-200', text: '¿A cuál de las personas presentes aquí jamás dejarías que se acerque a tu pareja?', level: 2, genderTarget: 'all' },

  // ——— Nivel 3: Se 😈 ———
  { id: 'q-l3-01', text: '¿Qué sería peor: que tu mamá te pille masturbándote o pillarla a ella?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-02', text: '¿Qué pensamiento sexual o atracción has tenido hacia un familiar tuyo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-03', text: 'Si nadie se entera, ¿qué le harías en la cama a la pareja de tu mejor amigo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-04', text: '¿Qué es lo más degradante que aceptaste en la cama solo por complacer a alguien?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-05', text: '¿Qué sentiste al acostarte con alguien sabiendo que tenía pareja?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-06', text: '¿Con quién te acostaste por pura calentura aun pareciéndote feo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-07', text: '¿Qué fotos o videos íntimos tuyos temes que se filtren en internet?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-08', text: '¿Qué pensamiento morboso has tenido con el papá o la mamá de un amigo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-09', text: '¿Qué parte del cuerpo de tu pareja te dio asco en plena intimidad?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-10', text: '¿A quién usaste solo para saciarte sabiendo que estaba enamorado/a de ti?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-11', text: '¿En quién pensabas la última vez que tuviste sexo con tu pareja?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-12', text: 'Si supieras quién se masturba pensando en ti, ¿a quién le pedirías explicaciones?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-13', text: '¿A quién de esta sala te llevarías a la cama esta noche y qué posición le harías?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-14', text: '¿Qué fotos o videos candentes tomaste a escondidas sin permiso?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-15', text: '¿Cómo te aprovechaste de que alguien estaba tomado/a para besarlo/a o tocarlo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-16', text: '¿Cuál es tu fantasía sexual más perturbadora que jamás has confesado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-17', text: '¿Con quién de los presentes irías a un cuarto oscuro y qué sería lo primero que harían?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-18', text: '¿De tus parejas sexuales, a cuántas consideras un error asqueroso?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-19', text: '¿En qué lugar prohibido o público tuviste sexo con riesgo de que te vieran?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-20', text: '¿Qué fue lo más sucio y placentero que te hicieron en la cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-21', text: '¿Qué fetiche o morbo secreto buscas en internet cuando estás solo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-22', text: '¿Qué fue lo más desastroso o vergonzoso que te pasó la primera vez que tuviste sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-23', text: '¿Con quiénes harías un trío si se diera la oportunidad esta noche?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-24', text: '¿Qué postura sexual te dejó el cuerpo adolorido y caminando raro?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-25', text: '¿Qué hiciste cuando se te rompió el condón dentro de una chica?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-26', text: '¿Por qué lloraste o gritaste descontrolada tras un orgasmo intenso?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-27', text: '¿Qué fetiche extremo has probado en privado y te dio pena admitir?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-28', text: '¿Quién casi te descubre teniendo sexo en un lugar público?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-29', text: '¿Cuánto pagaste o cuánto cobraste por sexo o contenido erótico?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-30', text: '¿Cómo hiciste para tener sexo en una habitación donde alguien más dormía?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-31', text: '¿Qué pensamiento bizarro se te cruzó por la mente en pleno clímax?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-32', text: '¿Qué locura íntima hiciste bajo el efecto del alcohol o sustancias?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-33', text: '¿Qué trato rudo o fetiche doloroso aceptaste solo por complacerlo?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-34', text: '¿Qué hiciste cuando se te vino todo en menos de un minuto?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-35', text: '¿Cuál es el juguete sexual más potente que tienes y cómo lo usas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-36', text: '¿Qué video prohibido tienes guardado bajo llave en tu celular?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-37', text: 'Si es obligatorio un trío con gente de esta sala, ¿a qué dos personas eliges?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-38', text: '¿En qué baño público o trabajo te masturbaste por no aguantar la calentura?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-39', text: '¿Qué fluido corporal en el sexo te causa repulsión probar o tocar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-40', text: '¿Cómo fue la noche de sexo que tuviste con un desconocido sin saber su nombre?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-41', text: '¿Con quién le fuiste infiel a tu pareja y por qué nunca te descubrieron?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-42', text: '¿Quién te pilló masturbándote con las manos en la masa y qué cara puso?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-43', text: '¿Qué fue lo más vulgar o caliente que dijiste al oído en la cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-44', text: '¿Con quién te acostaste solo para destruir emocionalmente a un tercero?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-45', text: '¿Con cuántas personas diferentes estuviste en un mismo fin de semana?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-46', text: '¿En qué lugar prohibido sueñas con tener sexo salvaje?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-47', text: '¿Cómo fue tu experiencia con el sexo anal y qué te dolió más?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-48', text: '¿Qué nota del 1 al 10 le das a tu mejor polvo y qué hizo tan especial?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-49', text: '¿Por qué te vestiste y te fuiste a mitad del acto con alguien que lo hacía pésimo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-50', text: '¿Qué mentira inventaste para acostarte con una mujer en la primera noche?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-51', text: '¿Qué compañero/a de trabajo o estudio te quita el sueño con fantasías eróticas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-52', text: '¿A quién le mandaste una foto de tu pene sin que te la hubiera pedido?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-53', text: '¿Qué disfraz o juego de roles te calienta más que cualquier otra cosa?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-54', text: '¿En qué momento te masturbaste pensando en el novio/a de tu amigo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-55', text: '¿Qué chupones o marcas en el cuerpo tuviste que tapar con maquillaje y mentiras?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-56', text: '¿Qué desastre ocurrió cuando intentaste tener sexo en una piscina, mar o ducha?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-57', text: '¿Qué dolor o incomodidad soportaste en silencio durante el sexo para no cortar el rollo?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-58', text: '¿Qué práctica sexual juraste jamás hacer y terminaste pidiéndola a gritos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-59', text: '¿Con qué persona mucho mayor te acostaste o quisiste acostarte?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-60', text: '¿Cómo te sentiste la última vez que te usaron como un pedazo de carne y te desecharon?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-61', text: '¿Qué lencería provocativa o nada llevas debajo de la ropa hoy?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-62', text: '¿Qué ataduras o azotes has probado en la cama y qué tanto te excitaron?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-63', text: '¿Por qué razón ridícula te bajó la calentura cuando ya estaban en ropa interior?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-64', text: '¿Por qué te masturbaste justo después de terminar de tener sexo con tu pareja?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-65', text: '¿A quién le exigiste que se bañara antes de poder tocarlo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-66', text: '¿Qué maniobra sexual incómoda hiciste en los asientos traseros de un auto?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-67', text: '¿Cómo fue tener sexo en la casa de tus suegros con ellos en la habitación de al lado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-68', text: '¿Qué fantasía sexual resultó ser una decepción incómoda en la vida real?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-69', text: '¿Con qué objeto extraño de tu casa te masturbaste por falta de un juguete?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-70', text: '¿Qué olor corporal o sudor de alguien te excita de forma inexplicable?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-71', text: '¿Por qué rompiste récord terminando en 30 segundos y qué le dijiste a ella?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-72', text: '¿Por qué te entró el llanto o la culpa después de tener un orgasmo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-73', text: '¿A quién elegirías para que se acueste con tu pareja mientras tú miras?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-74', text: '¿Qué trampa hiciste con el condón o anticonceptivos para tener sexo sin protección?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-75', text: '¿Qué audio caliente le mandaste a alguien gimiendo o pidiendo sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-76', text: '¿En qué baño sucio de discoteca tuviste relaciones apurado/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-77', text: '¿Dónde te gusta que te muerdan o jalen el pelo cuando estás en el clímax?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-78', text: '¿Qué nombre de un ex dijiste por error en plena cama con otra persona?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-79', text: '¿Qué golpe, calambre o lesión sufriste durante una sesión salvaje de sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-80', text: '¿Qué locura sexual cometiste diciendo que estabas borracho/a aunque estabas consciente?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-81', text: '¿Qué sueño húmedo tan real tuviste que te despertó en medio de un orgasmo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-82', text: '¿Qué tocamiento o atrevimiento hiciste en un autobús, cine o avión lleno de gente?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-83', text: '¿Qué baile erótico o striptease hiciste para impresionar a alguien?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-84', text: '¿Qué celos le tuviste al consolador o vibrador de tu pareja?', level: 3, genderTarget: 'H' },
  { id: 'q-l3-85', text: '¿Cuál fue tu récord de veces que te masturbaste o tuviste sexo en un solo día?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-86', text: '¿Por qué calambre o dolor absurdo tuviste que pausar el sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-87', text: '¿Qué experiencia erótica real tuviste o deseas tener con alguien de tu mismo sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-88', text: '¿Qué gemido o frase ridícula gritaste cuando estabas por terminar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-89', text: '¿A quién mirabas a los ojos mientras te tocabas disimuladamente en una fiesta?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-90', text: '¿Cuál es el fetiche más sucio sobre ti que nadie en esta sala sabe?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-91', text: '¿Qué prenda diminuta o atrevida te pusiste para provocar a alguien y cómo terminó la noche?', level: 3, genderTarget: 'M' },
  { id: 'q-l3-92', text: '¿Qué es lo más salvaje que le harías a tu crush si lo tuvieras amarrado a una cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-93', text: '¿Por qué tuviste sexo sin ganas solo por cumplir o para que te dejaran dormir?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-94', text: '¿Qué sonido o actitud de tu pareja en la cama te da ganas de salir corriendo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-95', text: '¿En qué fiesta te encerraste en el baño a masturbarte y quién te estaba esperando afuera?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-96', text: '¿Qué fue lo más caliente que mostraste en una videollamada o frente a una cámara?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-97', text: '¿Qué fue lo que más te excitó al verte en un espejo mientras tenías relaciones?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-98', text: '¿Qué comida probaste en la cama (crema, hielo, miel) y qué tan pegajoso terminó todo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-99', text: '¿En qué lugar saliste a la calle sin ropa interior sintiendo la adrenalina?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-100', text: 'Si tuvieras que tener sexo salvaje con alguien presente ahora mismo, ¿a quién eliges sin pensarlo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-101', text: '¿Qué es lo más oscuro o prohibido que has experimentado bajo los efectos de drogas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-102', text: '¿Con qué persona prohibida de tu propia familia sentiste una tensión morbosa en un momento a solas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-103', text: '¿Qué traición imperdonable le hiciste a una persona que confiaba ciegamente en ti?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-104', text: '¿Qué fue lo más bajo que hiciste estando desesperado/a por conseguir dinero o placer?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-105', text: '¿Qué adicción o vicio secreto sientes que se está saliendo por completo de tu control?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-106', text: '¿Con quién te acostaste sabiendo que esa persona estaba destruyendo su propio matrimonio o noviazgo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-107', text: '¿Qué fetiche sexual oscuro tienes que sientes que arruinaría tu reputación si saliera a la luz?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-108', text: '¿Qué locura salvaje hiciste bajo el efecto de sustancias de la que jamás le contarás a tu familia?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-109', text: '¿A quién de este grupo le quitarías la pareja en la cama si te diera una sola señal en privado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-110', text: '¿Qué es lo más humillante que grabaste o permitiste que grabaran durante una noche de descontrol?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-111', text: '¿En qué momento sentiste que habías cruzado todos tus límites morales y no hubo vuelta atrás?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-112', text: '¿Qué secreto podrías revelar ahora mismo que destruiría por completo una amistad en esta sala?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-113', text: '¿Con qué persona estuviste en la cama únicamente para causarle un trauma a un enemigo en común?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-114', text: '¿Qué fantasía morbosa involucra a la pareja de tu mejor amigo/a y qué tan lejos la has imaginado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-115', text: '¿Qué mentira atroz inventaste para justificar una noche entera desaparecida/o con otra persona?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-116', text: '¿Qué práctica extrema o peligrosa en la cama probaste y te asustó lo mucho que te gustó?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-117', text: '¿Qué fue lo más perturbador que viste o viviste en una fiesta clandestina o privada?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-118', text: '¿A qué persona manipulaste sexual o emocionalmente sabiendo el poder que tenías sobre su mente?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-119', text: '¿Qué es lo más inmoral que hiciste por pura venganza y hasta el día de hoy no te arrepientes?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-120', text: '¿Con quién tuviste sexo en un lugar sagrado, religioso o prohibido sin ningún tipo de respeto?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-121', text: '¿Qué sustancia o exceso te hizo despertar en una cama desconocida con pánico total?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-122', text: '¿Qué deseo retorcido tienes que no te atreves a buscar en internet por miedo a ser rastreado/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-123', text: '¿A quién le fuiste infiel en la misma casa o cama donde vivías con tu pareja?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-124', text: '¿Qué conversación o archivo en tu celular te destruiría la vida entera si se hace público hoy?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-125', text: '¿Qué es lo más repugnante que toleraste en la intimidad solo por no cortar la calentura?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-126', text: '¿Con qué persona que odias a muerte terminaste teniendo el sexo más salvaje de tu vida?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-127', text: '¿Qué juego sexual o trío se salió de control y terminó destruyendo un grupo de amigos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-128', text: '¿Qué dinero ajeno o ilegal usaste para pagar vicios, fiestas o escapadas secretas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-129', text: '¿A quién utilizaste como juguete desechable sabiendo que estaba en su peor momento emocional?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-130', text: '¿Qué secreto sobre una infidelidad ajena guardas para chantajear o tener poder sobre alguien?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-131', text: '¿Qué fue lo más peligroso que hiciste con alguien que apenas acababas de conocer en la calle o club?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-132', text: '¿En qué momento tocaste el fondo más sucio de tu vida y fingiste que nada había pasado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-133', text: '¿Qué fantasía de dominación, humillación o dolor físico te excita en secreto?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-134', text: '¿Con quién hiciste un pacto de silencio tras cometer una locura imperdonable juntos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-135', text: '¿Qué foto o video íntimo tienes en tu poder que sabes que no deberías conservar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-136', text: '¿Qué propuesta indecente o millonaria te hicieron a cambio de pasar la noche y qué tanto lo dudaste?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-137', text: '¿A quién viste en su momento más vulnerable y te aprovechaste para conseguir lo que querías?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-138', text: '¿Qué mentira sostienes sobre tu pasado que si se descubre te dejaría completamente solo/a?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-139', text: '¿Qué locura cometiste en un auto en movimiento que puso en riesgo la vida de los dos por pura calentura?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-140', text: '¿Con qué persona mayor o con autoridad tuviste un romance clandestino que rozaba lo prohibido?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-141', text: '¿Qué es lo más denigrante que aceptaste hacer por drogas, alcohol o favores en una fiesta?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-142', text: '¿Qué pecado íntimo le ocultas a tu confesor, terapeuta o mejor amigo porque sabes que te juzgarían?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-143', text: '¿A quién le juraste fidelidad mientras en tu mente ya estabas planeando acostarte con otra persona?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-144', text: '¿Qué morbo oscuro sentiste al enterarte de una tragedia o ruptura de una persona que envidiabas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-145', text: '¿Con quién de esta reunión tendrías una aventura clandestina de meses si prometen jamás hablar de ello?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-146', text: '¿Qué noche de excesos y sustancias sientes que te quitó un pedazo de alma?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-147', text: '¿Qué es lo más sádico o frío que has pensado al romperle el corazón a alguien en pedazos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-148', text: '¿Qué confesión te llevarías a la tumba si no existiera este juego en este preciso instante?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-149', text: '¿A qué persona presente le harías la propuesta sexual más indecente y sucia si estuviéramos solos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-150', text: 'Si tuvieras que salvar tu pellejo exponiendo el secreto más oscuro de alguien en esta sala, ¿el secreto de quién revelarías?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-151', text: '¿Qué vicio oscuro o adicción secreta mantienes viva que destruiría la imagen que tienen de ti?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-152', text: '¿Con qué persona prohibida de tu entorno cercano tuviste un encuentro sexual que juraron ocultar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-153', text: '¿Qué traición por dinero, estatus o placer cometiste contra alguien que te consideraba familia?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-154', text: '¿En qué lugar clandestino o peligroso compraste sustancias arriesgando tu seguridad física?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-155', text: '¿Qué fue lo más bajo que hiciste para evitar que una infidelidad tuya saliera a la luz?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-156', text: '¿Con quién te acostaste por puro rencor sabiendo que le destrozarías la vida a una tercera persona?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-157', text: '¿Qué fetiche oscuro o práctica tabú te excita pero te genera culpa inmediata tras el clímax?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-158', text: '¿Qué noche de drogas y desenfreno terminó en un hospital o con la policía cerca?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-159', text: '¿A quién de este grupo manipularías en la cama sin dudarlo si supieras que no hay consecuencias?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-160', text: '¿Qué video o audio ultra explícito tuyo existe en un teléfono ajeno y rezas porque no se filtre?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-161', text: '¿En qué momento de tu vida tocaste el fondo moral más asqueroso y nadie se enteró?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-162', text: '¿Qué secreto sexual de un familiar descubriste por accidente y te atormenta saberlo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-163', text: '¿Con qué persona estuviste en la cama únicamente por el morbo de que era un familiar o amigo de tu enemigo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-164', text: '¿Qué fantasía con múltiples personas involucra a gente de esta misma sala?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-165', text: '¿Qué mentira destructiva le dijiste a una persona enamorada para sacarle dinero o sexo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-166', text: '¿Qué juego sexual extremo probaste que rozó el peligro físico real?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-167', text: '¿Qué fue lo más turbio que presenciaste en una habitación privada de un motel o fiesta?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-168', text: '¿A quién utilizaste como juguete sexual sabiendo que estaba borracho/a o vulnerable?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-169', text: '¿Qué venganza fría y calculada ejecutaste contra alguien que te lastimó y cómo disfrutaste verlo sufrir?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-170', text: '¿Con qué persona comprometida de tu trabajo o estudio tuviste sexo en las mismas instalaciones?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-171', text: '¿Qué pérdida total de control por sustancias te hizo despertar sin ropa en un lugar desconocido?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-172', text: '¿Qué búsqueda aberrante en internet te daría pánico que la policía o tu familia revisara?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-173', text: '¿A quién le fuiste infiel en una fiesta donde tu pareja estaba en la habitación de al lado?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-174', text: '¿Qué conversación erótica o fotos comprometedoras tienes guardadas de la pareja de un conocido?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-175', text: '¿Qué es lo más degradante que aceptaste hacer en la intimidad a cambio de sustancias o favores?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-176', text: '¿Con qué persona tóxica o peligrosa tuviste una adicción sexual que no podías cortar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-177', text: '¿Qué trío u orgía terminó en gritos, peleas y traumas que aún no superas?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-178', text: '¿Qué dinero robado o sucio usaste para financiar noches de lujuria o excesos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-179', text: '¿A quién desechaste como basura tras conseguir acostarte con él/ella en una sola noche?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-180', text: '¿Qué infidelidad presenciaste y callaste a cambio de que no revelaran un secreto tuyo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-181', text: '¿Qué fue lo más arriesgado que hiciste con un completo desconocido sin usar ninguna protección?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-182', text: '¿En qué momento sentiste que habías perdido tu dignidad por completo por culpa de una calentura?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-183', text: '¿Qué fetiche que involucra dolor, asfixia o humillación te enciende en secreto?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-184', text: '¿Con quién hiciste un pacto de sangre o silencio tras cometer una falta grave juntos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-185', text: '¿Qué contenido erótico prohibido o privado tienes en tu nube que si se filtra arruina tu vida?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-186', text: '¿Qué propuesta sexual indecente de una persona con poder o dinero estuviste a punto de aceptar?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-187', text: '¿A quién viste llorar destrozado/a tras terminarle de la forma más fría y despiadada en la cama?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-188', text: '¿Qué doble vida mantienes en secreto que nadie de los que están aquí presentes sospecha?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-189', text: '¿Qué locura cometiste en un lugar público concurrido donde había familias o niños cerca?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-190', text: '¿Con qué figura de autoridad o persona casada mantuviste una aventura clandestina de meses?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-191', text: '¿Qué bajeza cometiste para conseguir sustancias o alcohol cuando ya no tenías dinero?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-192', text: '¿Qué pecado capital sientes que te define cuando estás completamente solo/a en la oscuridad?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-193', text: '¿A quién le rompiste la vida en mil pedazos y fingiste ser la víctima ante todos?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-194', text: '¿Qué morbo enfermizo sentiste al enterarte de los detalles sexuales de la pareja de tu mejor amigo?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-195', text: '¿Con cuál de las personas presentes aquí tendrías una noche de sexo salvaje y sin reglas esta misma noche?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-196', text: '¿Qué noche de descontrol extremo sientes que cambió tu personalidad para siempre?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-197', text: '¿Qué es lo más despiadado que has hecho en la intimidad solo por alimentar tu ego narcisista?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-198', text: '¿Qué secreto aterrador sobre ti te llevarás a la tumba si no lo confiesas en este juego?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-199', text: '¿A qué persona de este grupo llevarías a un motel ahora mismo si nadie pudiera enterarse jamás?', level: 3, genderTarget: 'all' },
  { id: 'q-l3-200', text: 'Si tuvieras que condenar a uno de los presentes a que todo su historial íntimo se haga público, ¿a quién elegirías?', level: 3, genderTarget: 'all' },
];